config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root  "directors#index" , as: 'home'
resources :directors do
  resources :soaps
end

resources :soaps do
  resources :comments
end
end

app/models/soap.rb
class Soap < ApplicationRecord
  belongs_to :director
  has_many :comments
end

app/controllers/soaps_controller.rb
class SoapsController < ApplicationController
  before_action :set_soap, only: [:show, :edit, :update, :destroy]

  # GET /soaps
  # GET /soaps.json
  def index
    @soaps = Soap.all
  end

  # GET /soaps/1
  # GET /soaps/1.json
  def show
  end

  # GET /soaps/new
  def new
    @soap = Soap.new
  end

  # GET /soaps/1/edit
  def edit
  end

  # POST /soaps
  # POST /soaps.json
  def create
    @director = Director.find(params[:director_id])
    @soaps = @director.soaps.create(soap_params)
    redirect_to director_path(@director)


  end

  # PATCH/PUT /soaps/1
  # PATCH/PUT /soaps/1.json
  def update
    respond_to do |format|
      if @soap.update(soap_params)
        format.html { redirect_to @soap, notice: 'Soap was successfully updated.' }
        format.json { render :show, status: :ok, location: @soap }
      else
        format.html { render :edit }
        format.json { render json: @soap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soaps/1
  # DELETE /soaps/1.json
  def destroy
    @soap.destroy
    respond_to do |format|
      format.html { redirect_to soaps_url, notice: 'Soap was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_soap
      @soap = Soap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def soap_params
      params.require(:soap).permit(:soap_name, :soap_age, :director_id)
    end
end

app/helpers/soaps_helper.rb
module SoapsHelper
end

app/views/soaps/_form.html.erb
<%= form_with(model: soap, local: true) do |form| %>
  <% if soap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(soap.errors.count, "error") %> prohibited this soap from being saved:</h2>

      <ul>
      <% soap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/soaps/edit.html.erb
<h1>Editing Soap</h1>

<%= render 'form', soap: @soap %>

<%= link_to 'Show', @soap, {:class => 'btn btn-default'} %> |
<%= link_to 'Back', soaps_path, {:class => 'btn btn-default'}%>

app/views/soaps/index.html.erb
<p id="notice"><%= notice %></p>
<hr>

<%= link_to 'Back', directors_path, :class => 'btn btn-default'%>

app/views/soaps/new.html.erb
<h1>New Soap</h1>

<%= render 'form', soap: @soap %>

<%= link_to 'Back', soaps_path %>

app/views/soaps/show.html.erb
<p id="notice"><%= notice %></p>


<h3>Reviews</h3>
<% @soap.comments.each do |comment| %>
  <div class="well">
  <p><strong><%= comment.title %></strong>: <%= comment.description %>
  <%= link_to '[x]', [comment.soap, comment],
           method: :delete,
           data: { confirm:'Are you sure?'} %></p>
  </div>
<% end %>

<hr>
<h3>Add Review</h3>
<%= form_for([@soap, @soap.comments.build]) do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field(:title,{:class => 'form-control'}) %>
</p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area(:description,{:class => 'form-control'}) %>
</p>
 <p>
  <%= f.submit({:class => 'btn btn-default'}) %>
</p>
<% end %>

<hr>

<%= link_to 'Back', directors_path, :class => 'btn btn-default'%>