config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root  "directors#index" , as: 'home'
resources :directors do
  resources :soaps
end

resources :soaps do
  resources :comments
end
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :soaps
  belongs_to :user, :optional => true
  validates :first_name, :presence =>true
  validates :last_name, :presence =>true
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new

  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Producer was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Producer was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Producer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:first_name,:last_name,:age)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_with(model: director, local: true) do |form| %>
  <% if director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% director.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing Producer</h1>
<script>
window.onclick = myFunction;

function myFunction() {
    document.getElementsByTagName("BODY")[0].style.backgroundColor = "#C7EDE4";
}
</script>

<%= form_for :director, url: director_path(@director), method: :patch do |f| %>
  <br><p>
    <%= f.label :first_name %><br>
    <%= f.text_field(:first_name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field(:last_name, {:class => 'form-control'})  %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

<br>
<%= link_to 'Show', @director, {:class => 'btn btn-default'} %> |
<%= link_to 'Back', directors_path, {:class => 'btn btn-default'} %>

app/views/directors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Producers</h1><br>
<img src="soaps.jpg" align= "right" width="400px" height="400px" alt="image">
<script>
window.onclick = myFunction;

function myFunction() {
    document.getElementsByTagName("BODY")[0].style.backgroundColor = "#C7EDE4";
}
</script>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directors.each do |director| %>
      <tr>
        <td><strong><%= director.first_name %></strong></td>

        <td>|<%= director.last_name %> <br> </td>



        <td><%= link_to 'Show', director, :class => 'btn btn-default'  %> |<br></td>
        <td><%= link_to 'Edit', edit_director_path(director),:class => 'btn btn-default'  %> |<br></td>
        <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producer', new_director_path, :class => 'btn btn-default'  %>

app/views/directors/new.html.erb
<h1>New Producer</h1>
<script>
window.onclick = myFunction;

function myFunction() {
    document.getElementsByTagName("BODY")[0].style.backgroundColor = "#C7EDE4";
}
</script>


<%= link_to 'Back', directors_path %>

<%= form_for :director, url: directors_path do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>

  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>
<script>
window.onclick = myFunction;

function myFunction() {
    document.getElementsByTagName("BODY")[0].style.backgroundColor = "#C7EDE4";
}
</script>

<h1>Producers</h1>
<p><strong><%= @director.first_name %> <%= @director.last_name %><%= @director.age  %></strong></p>
<hr>

 <h3>Soap</h3>
<% @director.soaps.each do |soap| %>
   <div class="well">
   <p><strong><%= soap.soap_name %></strong>: <%= soap.soap_age %>
   <%= link_to '[x]', [soap.director, soap],
            method: :delete,
            data: { confirm:'Are you sure?'} %></p>

    <%= link_to 'Reviews', soap, :class => 'btn btn-default' %>
   </div>
<% end %>

   <h3>Add Soap</h3>
<%= form_for([@director, @director.soaps.build]) do |f| %>
<p>
  <%= f.label :soap_name %><br>
  <%= f.text_field(:soap_name,{:class => 'form-control'}) %>
</p>

 <p>
  <%= f.submit({:class => 'btn btn-default'}) %>
</p>
<% end %>



<hr>
<%= link_to 'Edit', edit_director_path(@director), :class => 'btn btn-default' %> |
<%= link_to 'Back', directors_path, :class => 'btn btn-default' %>